steps:
  # 1. Install Dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # 2. Build Web Application
  - name: 'python:3.9'
    entrypoint: 'python3'
    args: ['build.py']

  # 3. Build Android APK (Debug)
  - name: 'node:18'
    entrypoint: 'npx'
    args: ['cap', 'sync', 'android']
  
  - name: 'reactnativecommunity/react-native-android'
    entrypoint: 'bash'
    dir: 'android'
    args:
      - '-c'
      - |
        chmod +x ./gradlew
        ./gradlew assembleDebug

  # 4. Run Robo Test (Firebase Test Lab)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'firebase'
      - 'test'
      - 'android'
      - 'run'
      - '--app'
      - 'android/app/build/outputs/apk/debug/app-debug.apk'
      - '--device'
      - 'model=Pixel2,version=28,locale=en,orientation=portrait'
      - '--timeout'
      - '90s'

  # 5. Deploy to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args: ['deploy', '--project', '$PROJECT_ID', '--only', 'hosting']

# Upload build artifacts
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts/$BUILD_ID'
    paths: 
      - 'dist/**'
      - 'android/app/build/outputs/apk/debug/app-debug.apk'

# Timeout
timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
